debug: false
management.endpoints.web.exposure.include: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: ehdrbs92
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true





---

#spring:
#  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none
# =======
#  sql.init.mode: always
